### ISSUE TITLE
Lighthouse Report

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/dicty-stock-center#747]
## Report

So I noticed a few problems that were reported by Lighthouse. Here are a few of them:

### Performance (TBT)
According to [this post](https://web.dev/lighthouse-total-blocking-time/?utm_source=lighthouse&utm_medium=cli) by [web.dev](https://web.dev) the best approach to improve total blocking time (TBT) is using the opportunities section in the Lighthouse report.
- Using next-gen image format like `JPEG 2000` could potentially save around 23kb of downloads
- Code splitting ([web.dev/code-splitting-suspense](https://web.dev/code-splitting-suspense/?utm_source=lighthouse&utm_medium=cli))

These two seem to be the largest contributors to the performance score.

### Performance (LCP)
According to this [post](https://web.dev/lcp/#how-to-improve-largest-contentful-paint-on-your-site) an LCP score is measured by looking at `img`, `video`, and `image` elements in `svg` files. From my observations of stockcenter, I've only identified `img` elements, which do not amount to much.

Looking at this paragraph from the linked post:
>  In addition to late-loading images and fonts, a page may add new elements to the DOM as new content becomes available. If any of these new elements is larger than the previous largest contentful element, a new PerformanceEntry will also be reported.

Since the stockcenter page loads a skeleton loader initially and then adds the content fetched by the GraphQL server, I believe this may be the cause for the low LCP score. Otherwise, the score would not make much sense as the stockcenter page does not use many images, and the ones used are very small in size.

### PWA/Accessibility
- Redundant `manifest.json` file used for PWAs
- `robots.txt` file seems invalid as it contains HTML
- Use `aria-label` for users with disabilities using screen readers

<br />

## Updating/Configuring Minimum Scores
I was able to find this [resource](https://www.foo.software/docs/lighthouse-check-github-action/examples#failing-workflows-by-enforcing-minimum-scores) that demonstrates configuring min scores for each test. Here's an example from the page:

```yml
name: Lighthouse
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://www.foo.software,https://www.foo.software/contact'
          # ... all your other inputs
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "50"
          minPerformanceScore: "50"
          minProgressiveWebAppScore: "50"
          minSeoScore: "50"
```
In this example, we see the `with` section that defines minimum scores for each of the section lighthouse tests the website against. In the case of stockcenter we will need to update `.github/workflows/lighthouse.yml` with the appropriate section to update scores accordingly.
